## <div align="center"> TUGAS LAB IS388 Data Analysis </div>
## <div align="center"> WEEK [03]: [Data Manipulation & SQL Basic Query]</div>
#### <div align="center"> Semester Ganjil 2024/2025 </div>
---

In [18]:
import datetime
import uuid

studentName = "Joyandro Gerard Diasz"
studentNIM = "00000158474"
studentClass = "B"

In [19]:
myDate = datetime.datetime.now()
myDevice = str(uuid.uuid1())

print("Name: \t\t{}".format(studentName))
print("NIM: \t\t{}".format(studentNIM))
print("NIM: \t\t{}".format(studentClass))
print("Start: \t\t{}".format(myDate))
print("Device ID: \t{}".format(myDevice))

Name: 		Joyandro Gerard Diasz
NIM: 		00000158474
NIM: 		B
Start: 		2026-09-12 16:18:27.992499
Device ID: 	ea0226a9-ae8a-11f1-ad8c-24b2b965c072

---

## <div align="center"> Unguided Lab </div>

### Enter Guided Lab Code Here:

In [20]:
import pandas as pd
import numpy as np
from datetime import datetime

daftar_saham = pd.read_csv("DaftarSaham.csv")
financial = pd.read_csv("DataFinancialSaham.csv")

## <div align="center"> Question 01 </div>

In [21]:
# Mengurutkan ListingDate dari paling awal
listing_ascending = daftar_saham.sort_values(
    by="ListingDate",
    ascending=True
)

print("Saham dengan Listing Date paling awal:")
display(
    listing_ascending[
        ["Code", "Name", "ListingDate"]
    ].head(1)
)


# Mengurutkan Code secara alfabet
code_ascending = daftar_saham.sort_values(
    by="Code",
    ascending=True
)

print("Code saham terakhir secara alfabet:")
display(
    code_ascending[
        ["Code", "Name"]
    ].tail(1)
)

Saham dengan Listing Date paling awal:

     Code                          Name ListingDate
691  SMCB  Solusi Bangun Indonesia Tbk.  1977-08-10

Code saham terakhir secara alfabet:

     Code                          Name
828  ZYRX  Zyrexindo Mandiri Buana Tbk.

In [22]:
code_descending = daftar_saham.sort_values(
    by="Code",
    ascending=False
)

display(code_descending[["Code", "Name"]].head(1))

     Code                          Name
828  ZYRX  Zyrexindo Mandiri Buana Tbk.

## <div align="center"> Question 02 </div>

In [23]:
financial.columns = financial.columns.str.capitalize()

print(financial.columns)

Index(['Symbol', 'Account', 'Type', '2020', '2021', '2022', '2023'], dtype='str')

In [24]:
daftar_saham["ListingDate"] = pd.to_datetime(
    daftar_saham["ListingDate"],
    format="mixed"
)

print(daftar_saham["ListingDate"].dtype)

datetime64[us]

In [25]:
daftar_filtered = daftar_saham[
    daftar_saham["ListingDate"]
    .dt.year
    .between(2020, 2023)
].copy()

display(
    daftar_filtered[
        ["Code", "Name", "ListingDate"]
    ].head()
)

    Code                           Name ListingDate
6   ADCP    Adhi Commuter Properti Tbk.  2021-05-21
11  ADMR  Adaro Minerals Indonesia Tbk.  2022-01-03
29  AMAN      Makmur Berkah Amanda Tbk.  2020-03-13
30  AMAR       Bank Amar Indonesia Tbk.  2020-01-09
33  AMMS       Agung Menjangan Mas Tbk.  2022-08-04

In [26]:
print("Jumlah saham:", len(daftar_filtered))

print(
    daftar_filtered["ListingDate"]
    .dt.year
    .value_counts()
    .sort_index()
)

Jumlah saham: 168
ListingDate
2020    51
2021    56
2022    57
2023     4
Name: count, dtype: int64

## <div align="center"> Question 03 </div>

In [27]:
sector_summary = (
    daftar_filtered
    .groupby("Sector")
    .agg(
        TotalShares=("Shares", "sum"),
        AverageMarketCap=("MarketCap", "mean")
    )
    .reset_index()
)

display(sector_summary)

                       Sector   TotalShares  AverageMarketCap
0             Basic Materials  1.432414e+11      5.051136e+12
1          Consumer Cyclicals  1.039696e+11      8.574483e+11
2      Consumer Non-Cyclicals  1.990927e+11      3.329177e+12
3                      Energy  8.350028e+10      8.789834e+12
4                  Financials  4.480469e+10      6.357990e+12
5                  Healthcare  9.235156e+10      4.795637e+12
6                 Industrials  1.311352e+10      2.223149e+11
7             Infrastructures  1.208381e+11      6.941151e+12
8    Properties & Real Estate  1.047231e+11      7.141361e+11
9                  Technology  1.439443e+12      1.873396e+13
10  Transportation & Logistic  2.599474e+10      7.428981e+11

## <div align="center"> Question 04 </div>

In [28]:
tahun_sekarang = datetime.now().year

daftar_saham["TotalTahunOperasi"] = (
    tahun_sekarang
    - daftar_saham["ListingDate"].dt.year
)

display(
    daftar_saham[
        [
            "Code",
            "Name",
            "ListingDate",
            "TotalTahunOperasi"
        ]
    ].head()
)

   Code                          Name ListingDate  TotalTahunOperasi
0  AALI       Astra Agro Lestari Tbk.  1997-12-09                 29
1  ABBA             Mahaka Media Tbk.  2002-04-03                 24
2  ABDA  Asuransi Bina Dana Arta Tbk.  1989-07-06                 37
3  ABMM            ABM Investama Tbk.  2011-12-06                 15
4  ACES   Ace Hardware Indonesia Tbk.  2007-11-06                 19

## <div align="center"> Question 05 </div>

In [29]:
merged_df = pd.merge(
    daftar_filtered,
    financial,
    left_on="Code",
    right_on="Symbol",
    how="inner"
)

display(merged_df.head())

print("Jumlah baris hasil merge:", len(merged_df))
print("Jumlah saham unik:", merged_df["Code"].nunique())

,Code,Name,ListingDate,Shares,ListingBoard,Sector,LastPrice,MarketCap,MinutesFirstAdded,MinutesLastUpdated,...,HourlyLastUpdated,DailyFirstAdded,DailyLastUpdated,Symbol,Account,Type,2020,2021,2022,2023
0,ADCP,Adhi Commuter Properti Tbk.,2021-05-21,2.222222e+10,Utama,Properties & Real Estate,64.0,1.422222e+12,2022-02-21 09:00:00,2023-01-06 15:59:00,...,2023-01-06 15:00:00,2021-05-21,2023-01-06,ADCP,Accounts Payable,BS,1.067771e+12,1.507989e+12,1.520111e+12,1.293411e+12
1,ADCP,Adhi Commuter Properti Tbk.,2021-05-21,2.222222e+10,Utama,Properties & Real Estate,64.0,1.422222e+12,2022-02-21 09:00:00,2023-01-06 15:59:00,...,2023-01-06 15:00:00,2021-05-21,2023-01-06,ADCP,Accounts Receivable,BS,4.232533e+10,4.169681e+10,2.964976e+10,1.925395e+10
2,ADCP,Adhi Commuter Properti Tbk.,2021-05-21,2.222222e+10,Utama,Properties & Real Estate,64.0,1.422222e+12,2022-02-21 09:00:00,2023-01-06 15:59:00,...,2023-01-06 15:00:00,2021-05-21,2023-01-06,ADCP,Accumulated Depreciation,BS,-4.000943e+09,-7.980027e+09,-1.215153e+10,-1.250373e+10
3,ADCP,Adhi Commuter Properti Tbk.,2021-05-21,2.222222e+10,Utama,Properties & Real Estate,64.0,1.422222e+12,2022-02-21 09:00:00,2023-01-06 15:59:00,...,2023-01-06 15:00:00,2021-05-21,2023-01-06,ADCP,Additional Paid In Capital,BS,NaN,0.000000e+00,5.663270e+10,5.663270e+10
4,ADCP,Adhi Commuter Properti Tbk.,2021-05-21,2.222222e+10,Utama,Properties & Real Estate,64.0,1.422222e+12,2022-02-21 09:00:00,2023-01-06 15:59:00,...,2023-01-06 15:00:00,2021-05-21,2023-01-06,ADCP,Allowance For Doubtful Accounts Receivable,BS,-1.026560e+09,-1.096787e+09,-1.035587e+09,-2.096447e+09

Jumlah baris hasil merge: 9509
Jumlah saham unik: 64

In [30]:
merged_df["ListingYear"] = (
    merged_df["ListingDate"].dt.year
)

In [31]:
merged_unique = merged_df.drop_duplicates(
    subset=["Code"]
)

In [32]:
average_last_price = (
    merged_unique
    .groupby(
        ["Sector", "ListingYear"]
    )["LastPrice"]
    .mean()
    .reset_index(
        name="AverageLastPrice"
    )
)

average_last_price["AverageLastPrice"] = (
    average_last_price["AverageLastPrice"]
    .round(2)
)

display(average_last_price)

                       Sector  ListingYear  AverageLastPrice
0             Basic Materials         2020            416.00
1             Basic Materials         2021            561.00
2          Consumer Cyclicals         2020           3150.00
3          Consumer Cyclicals         2021            528.50
4          Consumer Cyclicals         2022            753.67
5      Consumer Non-Cyclicals         2020            754.33
6      Consumer Non-Cyclicals         2021           1858.60
7      Consumer Non-Cyclicals         2022            650.88
8                      Energy         2020            605.00
9                      Energy         2021           2611.33
10                     Energy         2022           1560.00
11                 Financials         2020           1351.00
12                 Financials         2021           2402.50
13                 Financials         2022            444.00
14                 Healthcare         2020           3037.00
15                 Healthcare         2021            755.00
16                 Healthcare         2022            786.67
17            Infrastructures         2021            705.00
18            Infrastructures         2022            530.50
19   Properties & Real Estate         2020            441.33
20   Properties & Real Estate         2021             64.00
21   Properties & Real Estate         2022            138.00
22                 Technology         2020           3300.00
23                 Technology         2021          19218.00
24                 Technology         2022            221.33
25  Transportation & Logistic         2022            266.00

----

## <div align="center"> Conclusion </div>

### Enter Your Conclusion Here:

----

In [33]:
studentName2 = "Nama2"
studentNIM2 = "NIM2"
studentClass2 = "Class2"

In [34]:
print("Name: \t\t{}".format(studentName2))
print("NIM: \t\t{}".format(studentNIM2))
print("NIM: \t\t{}".format(studentClass2))
print("End: \t\t{}".format(myDate))
print("Device ID: \t{}".format(myDevice))

Name: 		Nama2
NIM: 		NIM2
NIM: 		Class2
End: 		2026-09-12 16:18:27.992499
Device ID: 	ea0226a9-ae8a-11f1-ad8c-24b2b965c072

----

## <div align="center"> Reference </div>

### Input Your Reference Here  (Jika ada):

----