## <div align="center"> TUGAS LAB IS388 Data Analysis </div>
## <div align="center"> WEEK [XX]: [Topic]</div>
#### <div align="center"> Semester Ganjil 2024/2025 </div>
---

In [1]:
import datetime
import uuid

studentName = "Joyandro Gerard Diasz"
studentNIM = "00000158474"
studentClass = "B"

In [2]:
myDate = datetime.datetime.now()
myDevice = str(uuid.uuid1())

print("Name: \t\t{}".format(studentName))
print("NIM: \t\t{}".format(studentNIM))
print("NIM: \t\t{}".format(studentClass))
print("Start: \t\t{}".format(myDate))
print("Device ID: \t{}".format(myDevice))

Name: 		Joyandro Gerard Diasz
NIM: 		00000158474
NIM: 		B
Start: 		2026-09-12 16:02:01.998982
Device ID: 	9e4f7ffd-ae88-11f1-869f-24b2b965c072

---

## <div align="center"> Unguided Lab </div>

### Enter Guided Lab Code Here:

In [3]:
import pandas as pd
import numpy as np
from datetime import datetime

daftar_saham = pd.read_csv("DaftarSaham.csv")
financial = pd.read_csv("DataFinancialSaham.csv")

---
#### Soal 01

In [ ]:
## <div align="center"> Soal 01 </div>

In [4]:
# Mengurutkan ListingDate dari paling awal
listing_ascending = daftar_saham.sort_values(
    by="ListingDate",
    ascending=True
)

print("Saham dengan Listing Date paling awal:")
display(
    listing_ascending[
        ["Code", "Name", "ListingDate"]
    ].head(1)
)


# Mengurutkan Code secara alfabet
code_ascending = daftar_saham.sort_values(
    by="Code",
    ascending=True
)

print("Code saham terakhir secara alfabet:")
display(
    code_ascending[
        ["Code", "Name"]
    ].tail(1)
)

Saham dengan Listing Date paling awal:

     Code                          Name ListingDate
691  SMCB  Solusi Bangun Indonesia Tbk.  1977-08-10

Code saham terakhir secara alfabet:

     Code                          Name
828  ZYRX  Zyrexindo Mandiri Buana Tbk.

In [5]:
code_descending = daftar_saham.sort_values(
    by="Code",
    ascending=False
)

display(code_descending[["Code", "Name"]].head(1))

     Code                          Name
828  ZYRX  Zyrexindo Mandiri Buana Tbk.

----

## <div align="center"> Conclusion </div>

### Enter Your Conclusion Here:

----

In [18]:
studentName2 = "Nama2"
studentNIM2 = "NIM2"
studentClass2 = "Class2"

In [20]:
print("Name: \t\t{}".format(studentName2))
print("NIM: \t\t{}".format(studentNIM2))
print("NIM: \t\t{}".format(studentClass2))
print("End: \t\t{}".format(myDate))
print("Device ID: \t{}".format(myDevice))

Name: 		Nama2
NIM: 		NIM2
NIM: 		Class2
End: 		2024-08-20 10:12:14.272617
Device ID: 	ff98d422-5ea1-11ef-8ac7-0045e2d68e9e

----

## <div align="center"> Reference </div>

### Input Your Reference Here  (Jika ada):

----